---
metadata:
    prefix: "oc-vlan"
    parser: TextParser

vlan:
    _parse: unnecessary
    config:
        _parse: unnecessary
        vlan-id:
            _parse:
                mode: search
                regexp: "^\\W*encapsulation dot1q (?P<value>[0-9]+)"
                from: "{{ bookmarks['parent'] }}"
