---
metadata:
    processor: XMLParser

routed-vlan:
    _process: unnecessary
    config:
        _process: unnecessary
        enabled:
            _process: unnecessary
        vlan:
            _process: unnecessary
