---
metadata:
    processor: TextTree

ipv4:
    _process: unnecessary
    config:
        _process: unnecessary
        enabled:
            _process:
                - mode: is_absent
                  path: "switchport"
        mtu:
            _process: not_implemented
    addresses:
        _process: unnecessary
        address:
            _process:
                - path: "ip.address"
                  regexp: "(?P<value>(?P<ip>.*))\\/(?P<prefix>\\d+)"
            ip:
                _process: unnecessary
            config:
                _process: unnecessary
                ip:
                    _process:
                        - value: "{{ extra_vars.address.ip }}"
                prefix-length:
                    _process:
                        - value: "{{ extra_vars.address.prefix }}"
            vrrp:
                _process: not_implemented
                vrrp-group:
                    _process: not_implemented
                    virtual-router-id:
                        _process: not_implemented
                    config:
                        _process: not_implemented
                        virtual-address:
                            _process: not_implemented
                        priority:
                            _process: not_implemented
                        preempt:
                            _process: not_implemented
                        advertisement-interval:
                            _process: not_implemented
                        virtual-router-id:
                            _process: not_implemented
                        preempt-delay:
                            _process: not_implemented
                        accept-mode:
                            _process: not_implemented
    unnumbered:
        _process: not_implemented
        config:
            _process: not_implemented
            enabled:
                _process: not_implemented
        interface-ref:
            _process: not_implemented
            config:
                _process: not_implemented
                interface:
                    _process: not_implemented
                subinterface:
                    _process: not_implemented
    neighbors:
        _process: not_implemented
        neighbor:
            _process: not_implemented
            ip:
                _process: not_implemented
            config:
                _process: not_implemented
                ip:
                    _process: not_implemented
                link-layer-address:
                    _process: not_implemented
