---
metadata:
    parser: TextExtractor

ipv4:
    _parse: unnecessary
    config:
        _parse: unnecessary
        enabled:
            _parse:
                mode: is_absent
                regexp: "(?P<value>^\\W*switchport$)"
                from: "{{ bookmarks['parent'] }}"
        mtu:
            _parse: not_implemented
    addresses:
        _parse: unnecessary
        address:
            _parse:
                mode: block
                regexp: "(?P<block>ip address (?P<key>(?P<ip>.*))\\/(?P<prefix>\\d+))(?P<secondary> secondary)*"
                from: "{{ bookmarks['parent'] }}"
            ip:
                _parse: unnecessary
            config:
                _parse: unnecessary
                ip:
                    _parse:
                        mode: value
                        value: "{{ extra_vars.ip }}"
                prefix_length:
                    _parse:
                        mode: value
                        value: "{{ extra_vars.prefix }}"
            vrrp:
                _parse: not_implemented
                vrrp_group:
                    _parse: not_implemented
                    virtual_router_id:
                        _parse: not_implemented
                    config:
                        _parse: not_implemented
                        virtual_address:
                            _parse: not_implemented
                        priority:
                            _parse: not_implemented
                        preempt:
                            _parse: not_implemented
                        advertisement_interval:
                            _parse: not_implemented
                        virtual_router_id:
                            _parse: not_implemented
                        preempt_delay:
                            _parse: not_implemented
                        accept_mode:
                            _parse: not_implemented
    unnumbered:
        _parse: not_implemented
        config:
            _parse: not_implemented
            enabled:
                _parse: not_implemented
        interface_ref:
            _parse: not_implemented
            config:
                _parse: not_implemented
                interface:
                    _parse: not_implemented
                subinterface:
                    _parse: not_implemented
    neighbors:
        _parse: not_implemented
        neighbor:
            _parse: not_implemented
            ip:
                _parse: not_implemented
            config:
                _parse: not_implemented
                ip:
                    _parse: not_implemented
                link_layer_address:
                    _parse: not_implemented
